get_filename_component(VCPKG_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
# Package config file for external package/TPL 'MPI'
#
# Generated by CMake, do not edit!

# Guard against multiple inclusion
if (TARGET TPL::MPI::all_libs)
  return()
endif()

add_library(TPL::MPI::all_libs INTERFACE IMPORTED)
target_include_directories(TPL::MPI::all_libs SYSTEM
  INTERFACE "${VCPKG_IMPORT_PREFIX}/include"
  )

