cmake_policy(SET CMP0012 NEW)
cmake_policy(SET CMP0057 NEW)
if(NOT "OFF")
    if(NOT CMAKE_CXX_COMPILER_LOADED)
        message(WARNING "Linking to GDAL may need CXX to be enabled.")
    endif()
    if(DEFINED CMAKE_MODULE_PATH)
        set(_gdal_module_path_backup "${CMAKE_MODULE_PATH}")
    endif()
    include(CMakeFindDependencyMacro)
# gdal needs a pkg-config tool. A host dependency provides pkgconf.
get_filename_component(vcpkg_host_prefix "${CMAKE_CURRENT_LIST_DIR}/../../../arm64-linux" ABSOLUTE)
list(APPEND CMAKE_PROGRAM_PATH "${vcpkg_host_prefix}/tools/pkgconf")
include("${CMAKE_CURRENT_LIST_DIR}/DefineFindPackage2.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GdalFindModulePath.cmake")
find_dependency(Threads)
find_dependency(CURL 7.68)
find_dependency(Iconv )
find_dependency(LibXml2 )
find_dependency(EXPAT  NAMES expat CONFIGS expat-config.cmake)
find_dependency(PROJ CONFIG)
find_dependency(ZSTD  NAMES zstd CONFIGS zstdConfig.cmake)
find_dependency(GeoTIFF  NAMES GeoTIFF CONFIGS geotiff-config.cmake)
find_dependency(PNG 1.6)
find_dependency(GIF )
find_dependency(JSONC  NAMES json-c CONFIGS json-c-config.cmake)
find_dependency(QHULL  NAMES Qhull CONFIGS QhullConfig.cmake)
find_dependency(LERC )
find_dependency(PCRE2 )
find_dependency(SQLite3 3.31)
find_dependency(SPATIALITE 4.1.2)
find_dependency(LibKML COMPONENTS DOM ENGINE)
find_dependency(HDF5 COMPONENTS C)
find_dependency(WebP  NAMES WebP CONFIGS WebPConfig.cmake)
find_dependency(GEOS 3.8 NAMES GEOS CONFIGS geos-config.cmake)
find_dependency(NetCDF 4.7 NAMES netCDF CONFIGS netCDFConfig.cmake)
find_dependency(PostgreSQL )
find_dependency(OpenJPEG 2.3.1 MODULE)

    if(DEFINED _gdal_module_path_backup)
        set(CMAKE_MODULE_PATH  "${_gdal_module_path_backup}")
    else()
        unset(CMAKE_MODULE_PATH)
    endif()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/GDAL-targets.cmake")
