set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v142) # 使用 Visual Studio 2019 的工具集
set(VCPKG_CMAKE_SYSTEM_VERSION "10.0") # 指定使用sdk 10

set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -DBOOST_USE_WINAPI_VERSION=BOOST_WINAPI_VERSION_WIN7")
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -DBOOST_USE_WINAPI_VERSION=BOOST_WINAPI_VERSION_WIN7")