# We can't create the same interface imported target multiple times, CMake will complain if we do
# that. This can happen if the find_package call is done in multiple different subdirectories.
if(TARGET WrapLibArchive::WrapLibArchive)
    set(WrapLibArchive_FOUND TRUE)
    return()
endif()

find_package(LibArchive 3.5)

if (NOT LibArchive_FOUND)
    set(WrapLibArchive_FOUND FALSE)
    return()
endif()

add_library(WrapLibArchive::WrapLibArchive INTERFACE IMPORTED)
target_link_libraries(WrapLibArchive::WrapLibArchive INTERFACE ${LibArchive_LIBRARIES})
target_include_directories(WrapLibArchive::WrapLibArchive INTERFACE ${LibArchive_INCLUDE_DIRS})
set(WrapLibArchive_FOUND TRUE)
if(TARGET BZip2::BZip2)
	set_property(TARGET BZip2::BZip2 PROPERTY _qt_no_promote_global TRUE)
endif()
if(TARGET Threads::Threads)
	set_property(TARGET Threads::Threads PROPERTY _qt_no_promote_global TRUE)
endif()
if(TARGET OpenSSL::Crypto)
	set_property(TARGET OpenSSL::Crypto PROPERTY _qt_no_promote_global TRUE)
endif()
if(TARGET zstd::libzstd)
	set_property(TARGET zstd::libzstd PROPERTY _qt_no_promote_global TRUE)
endif()
if(TARGET zstd::libzstd_shared)
	set_property(TARGET zstd::libzstd_shared PROPERTY _qt_no_promote_global TRUE)
endif()
if(TARGET zstd::libzstd_static)
	set_property(TARGET zstd::libzstd_static PROPERTY _qt_no_promote_global TRUE)
endif()
if(TARGET ZLIB::ZLIB)
	set_property(TARGET ZLIB::ZLIB PROPERTY _qt_no_promote_global TRUE)
endif()
