QT.repparser_private.VERSION = 6.9.1
QT.repparser_private.name = QtRepParser
QT.repparser_private.module =
QT.repparser_private.libs = $$QT_MODULE_LIB_BASE
QT.repparser_private.includes = 
QT.repparser_private.frameworks = 
QT.repparser_private.depends = 
QT.repparser_private.uses = 
QT.repparser_private.module_config = v2 internal_module
QT.repparser_private.enabled_features = 
QT.repparser_private.disabled_features = 
