QT.appman_qml_systemui_private.VERSION = 6.9.1
QT.appman_qml_systemui_private.name = QtAppManQmlSystemUIPrivate
QT.appman_qml_systemui_private.module =
QT.appman_qml_systemui_private.libs = $$QT_MODULE_LIB_BASE
QT.appman_qml_systemui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtAppManQmlSystemUIPrivate/6.9.1 $$QT_MODULE_INCLUDE_BASE/QtAppManQmlSystemUIPrivate/6.9.1/QtAppManQmlSystemUIPrivate
QT.appman_qml_systemui_private.frameworks = 
QT.appman_qml_systemui_private.depends = appman_qml_systemui
QT.appman_qml_systemui_private.uses = 
QT.appman_qml_systemui_private.module_config = v2 staticlib internal_module
QT.appman_qml_systemui_private.enabled_features = 
QT.appman_qml_systemui_private.disabled_features = 
