set(_vtk_module_import_prefix "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
set_property(TARGET "VTKCompileTools::WrappingTools" PROPERTY "INTERFACE_vtk_module_exclude_wrap" "TRUE")
set_property(TARGET "VTKCompileTools::WrappingTools" PROPERTY "INTERFACE_vtk_module_depends" "")
set_property(TARGET "VTKCompileTools::WrappingTools" PROPERTY "INTERFACE_vtk_module_private_depends" "")
set_property(TARGET "VTKCompileTools::WrappingTools" PROPERTY "INTERFACE_vtk_module_optional_depends" "")
set_property(TARGET "VTKCompileTools::WrappingTools" PROPERTY "INTERFACE_vtk_module_implements" "")
set_property(TARGET "VTKCompileTools::WrappingTools" PROPERTY "INTERFACE_vtk_module_implementable" "FALSE")
set_property(TARGET "VTKCompileTools::WrappingTools" PROPERTY "INTERFACE_vtk_module_library_name" "vtkWrappingTools")
set_property(TARGET "VTKCompileTools::WrappingTools" PROPERTY "INTERFACE_vtk_module_headers" "${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParse.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseAttributes.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseData.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseDependencyTracking.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseExtras.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseHierarchy.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseMain.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseMangle.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseMerge.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParsePreprocess.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseString.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseSystem.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkParseType.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkWrap.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkWrapText.h;${_vtk_module_import_prefix}/install/vtk-compile-tools/vtk-9.3/vtkWrappingToolsModule.h")
unset(_vtk_module_import_prefix)
